### ISSUE TITLE
Keeping the num lock on using startup script won't send keys to howm?

### ISSUE THREAD

**Issue by neo1691** [HarveyHunt/howm#11]
I had this in my xinitrc
numlockx &
Which made sure that my numlock was on when I boot into my wm. This was causing my keys to do nothing in howm. Can somebody reproduce this bug?

Happens in the latest build on develop branch.

**Comment by HarveyHunt** [comment]
Does this still happen?

**Comment by neo1691** [comment]
Not using howm anymore. But last time I checked it did happen

On Fri, Jul 24, 2015 at 8:34 PM, Harvey Hunt <notifications@github.com>
wrote:

> Does this still happen?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HarveyHunt/howm/issues/11#issuecomment-124552424>.
>



-- 
Regards,
Anubhav Yadav
KPIT Technologies,
Pune.

**Comment by HarveyHunt** [comment]
Closing this as keypresses are now handled by ```sxhkd```.
