### ISSUE TITLE
Invisible windows, multiple context menus

### ISSUE THREAD

**Issue by anshulk** [HarveyHunt/howm#14]
Windows seem to behave weirdly - initially plain white with no content visible, appears on double click though. 

Right clicking multiple times gives multiple context menus with none responding to mouse click.

![Screenshot](https://cloud.githubusercontent.com/assets/3637620/4179565/e1ed61c8-36cb-11e4-96cf-d5022400039a.png)

**Comment by HarveyHunt** [comment]
This was fixed in https://github.com/HarveyHunt/howm/commit/98eb56ef0e28ffc3b1cb8ce81e2b38cab4a6509e.
